import 'package:flutter/material.dart';
import 'package:flutter/material.dart';
import 'package:gymjoe/Auth/login.dart';
import 'package:gymjoe/splash1.dart';



void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home:  Splash1(),

    );
  }
}

